spring:
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
  redis:
    host: redis
  rabbitmq:
    host: mq-dev
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
logging:
  level:
    com.jiangjj: DEBUG