spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://db-dev:3306/testdb?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1.0
  redis:
    host: redis
  rabbitmq:
    host: mq-dev
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9100
feign:
  hystrix:
    enable: true
