version:  '3'
services:
  db-dev:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
    - "3306:3306"

  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  mq-dev:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  config-server:
    build: config-server
    image: jiangjj/config-server
    restart: always
    ports:
      - "8888:8888"

  service-discovery:
    build: service-discovery
    image: jiangjj/service-discovery
    restart: always
    ports:
      - "8761:8761"

  oauth2:
    build: oauth2
    image: jiangjj/oauth2
    restart: always

  api-gateway:
    build: zuul
    image: jiangjj/zuul
    restart: always
    ports:
      - "9000:9000"

  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - "9411:9411"
    environment:
      RABBIT_ADDRESSES: "mq-dev"

  breaker-dashboard:
    build: breaker-dashboard
    image: jiangjj/breaker-dashboard
    restart: always
    ports:
    - "9090:9090"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    restart: always
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./elk/elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    restart: always
    ports:
    - "9601:9601"
    volumes:
    - ./elk/logstash/config-dir:/config-dir
    command: logstash -f /config-dir
    depends_on:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    restart: always
    ports:
    - "5601:5601"
    depends_on:
    - elasticsearch