logging:
  level:
    com.jiangjj: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
server:
  port: 9000
zuul:
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 60000
spring:
  zipkin:
    base-url: http://zipkin:9411/
#    sender:
#      type: rabbit
    sleuth:
      sampler:
        probability: 1.0
  rabbitmq:
    host: mq-dev