version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    container_name: logstash
    restart: always
    ports:
      - "9601:9601"
    volumes:
    - ./logstash/config-dir:/config-dir
    command: logstash -f /config-dir
    depends_on:
    - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    container_name: kibana
    restart: always
    ports:
    - "5601:5601"
    depends_on:
    - elasticsearch