spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://db-dev:3306/testdb?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411/
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    stream:
      bindings:
        output:
                  destination: orgChangeTopic
                  content-type: application/json
  rabbitmq:
    host: mq-dev
  redis:
    host: redis
logging:
  level:
    com.jiangjj: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9200
signing:
  key: thisissigningkey
#sharding:
#  jdbc:
#    datasource:
#      names: master0,master1,master0slave0,master0slave1,master1slave0,master1slave1
#      master0:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3306/master0?useSSL=false
#        username: root
#        password: mysql
#      master0slave0:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3306/master0slave0?useSSL=false
#        username: root
#        password: mysql
#      master0slave1:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3306/master0slave1?useSSL=false
#        username: root
#        password: mysql
#      master1:
#        type: org.apache.commons.dbcp.BasicDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3306/master1?useSSL=false
#        username: root
#        password: mysql
#        master1slave0:
#          type: org.apache.commons.dbcp.BasicDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://db-dev:3306/master1slave0?useSSL=false
#          username: root
#          password: mysql
#        master1slave1:
#          type: org.apache.commons.dbcp.BasicDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://db-dev:3306/master1slave1?useSSL=false
#          username: root
#          password: mysql
#    config:
#      sharding:
#        default-database-strategy:
#          inline:
#            sharding-column: id
#            algorithm-expression: master$->{id % 2}
#        tables:
#          t_org:
#          actual-data-nodes: master$->{0..1}.t_org$->{0..1}
#          table-strategy.inline.sharding-column: name
#          table-strategy.inline.algorithm-expression: t_org$->{name.hashCode() % 2}
#          key-generator-column-name: name
#        master-slave-rules:
#          ds0:
#            master-data-source-name: master0
#            slave-data-source-names: master0slave0, master0slave1
#          ds1:
#            master-data-source-name: master1
#            slave-data-source-names: master1slave0, master1slave1
#sharding:
#  jdbc:
#    data-sources:
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3001/master0?useSSL=false
#        username: root
#        password: root
#      ds0_slave0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3002/master0?useSSL=false
#        username: root
#        password: root
#      ds0_slave1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3003/master0?useSSL=false
#        username: root
#        password: root
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3004/master1?useSSL=false
#        username: root
#        password: root
#      ds1_slave0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3005/master1?useSSL=false
#        username: root
#        password: root
#      ds1_slave1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://db-dev:3006/master1?useSSL=false
#        username: root
#        password: root
#
#    sharding-rule:
#      tables:
#        t_org:
#          actual-data-nodes: master${0..1}.t_org${0..1}
#          tablen-trategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: t_org${id % 2}
#          key-generator-column-name: id
#
#      binding-tables:
#      - t_order
#
#      default-database-strategy:
#        inline:
#          sharding-nolumn: name
#          algorithm-expression: master${name.hashCode() % 2}
#
#      default-table-strategy:
#        none:
#      default-key-generator-class-name: io.shardingsphere.core.keygen.DefaultKeyGenerator
#
#      master-slave-rules:
#        ms_ds0:
#          master-data-source-name: ds0
#          slave-data-source-names:
#          - ds0_slave0
#          - ds0_slave1
#          load-balance-algorithm-type: ROUND_ROBIN
#          config-map:
#            master-slave-key0: master-slave-value0
#        ms_ds1:
#          master-data-source-name: ds1
#          slave-data-source-names:
#          - ds1_slave0
#          - ds1_slave1
#          load-balance-algorithm-type: ROUND_ROBIN
#          config-map:
#            master-slave-key1: master-slave-value1
#
#      props:
#        sql.show: true

sharding:
  data-sources:      # 注意命名格式
    ds_master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db-dev:3001/master0?useSSL=false
      username: root
      password: root
    ds_slave_0:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db-dev:3002/master0?useSSL=false
      username: root
      password: root
    ds_slave_1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://db-dev:3003/master0?useSSL=false
      username: root
      password: root
  master-slave-rule:
    name: ds_ms
    master-data-source-name: ds_master
    slave-data-source-names: ds_slave_0, ds_slave_1
    zhload-balance-algorithm-type: round_robin