my:
  message: myMessage1
  encryptMessage: '{cipher}a605a2097c68da8a4925b7bf8a04b3c6ab850713b1a2a0c8a4a331b557cbd9f8'
server:
  port: 8081
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    username: super
    password: postgresql
    url: jdbc:postgresql://localhost:5432/testdb