my:
  message: myMessage1
  encryptMessage: '{cipher}a605a2097c68da8a4925b7bf8a04b3c6ab850713b1a2a0c8a4a331b557cbd9f8'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true